config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'posts/new'
  get 'posts/create'
  get 'posts/index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#delete'
  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  #attr_accessor :remember_token
  has_secure_password
  before_create :remember
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  #validates :password, presence: true, length: { minimum: 6 }

  def remember
  	token = SecureRandom.urlsafe_base64
  	self.remember_digest = Digest::SHA1.hexdigest(token.to_s)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def remember(user)
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_digest] = user.remember_digest
  end

  def log_out
    #forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    #debugger
    if @post.save
      redirect_to posts_url
    end
  end

  def index
    @posts = Post.all
    #@author = User.find(params[:id])
  end

  private

  def logged_in_user
    unless !current_user.nil?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to posts_url
    end
  end

  def delete
    log_out
    redirect_to posts_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_digest])
        log_in user
        @current_user = user
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_user.nil? %>
      <%= link_to "Log out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", login_path %>
    <% end %>
    <%= link_to "Posts", posts_path %>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% @posts.each do |p| %>
  <h3><%= p.title %></h3>
  <p><%= p.body %></p>
  <% if current_user %>
    <p>Author: <%= p.user.name %></p>
  <% end %>
  <hr>
<% end %>

<%= link_to "Add Post", posts_new_path %>

app/views/posts/new.html.erb
<h1>New Posts</h1>

<%= bootstrap_form_for(@post, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :body %>
  <%= f.submit 'Post' %>
<% end %>
<br>
<%= link_to "Back", posts_path %>